# Generated by Django 5.0.4 on 2024-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacliente',
            options={'verbose_name': 'ContaCliente', 'verbose_name_plural': 'ContasClientes'},
        ),
        migrations.AddField(
            model_name='contacliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
    ]
