# Generated by Django 5.0.4 on 2024-05-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contacliente_options_contacliente_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo'),
        ),
    ]
