# Generated by Django 5.0.4 on 2024-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default=1, max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
